# Before doing a restore, you may want to clear the database and search engine of the destination: 
# Solr Pod: 
# curl -X POST -d '<delete><query>*:*</query></delete>' http://localhost:8983/solr/nico/update?commitWithin=1000&overwrite=true&wt=xml
# Postgres Pod: 
# psql nico -c 'delete from a; delete from d; delete from c;'
---
- name: For each file
  include_tasks: nico_site.yml
  with_fileglob: 
    - "{{ NICO_SITE_RESTORE_DIR_ENUS }}/{{ DATA_NAME_VAR }}*"

