---

- name: Install the nico-site source code and watch service on the target. 
  hosts: localhost
  vars: 
    PROJECT_NAME: nico-site
    GITHUB_ORG: "{{ PROJECT_NAME }}"
    PROJECT_REPO: "git@github.com:computate/nico-site.git"
    PROJECT_SRC: "{{ playbook_dir }}"
    PROJECT_STATIC_REPO: "git@github.com:computate/nico-site-static.git"
    PROJECT_ANSIBLE_REPO: "git@github.com:computate/nico-site-ansible.git"
  tasks: 
#    - include_role:
#        name: computate.computate_postgres
#    - include_role:
#        name: computate.computate_zookeeper
#    - include_role:
#        name: computate.computate_solr
    - include_role:
        name: computate.computate_project
      vars: 
        PROJECT_JAVA_PACKAGE: org.computate.nico.enus
        PROJECT_SERVICES: 
          - PROJECT_NAME: "{{ PROJECT_NAME }}"
            PROJECT_SRC: "{{ playbook_dir }}"
            PROJECT_JAVA_PACKAGE: org.computate.nico.enus

