---
- name: Restore the nico-site page-design data
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }
- name: Restore the nico-site html-part data
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }
- name: Restore the nico-site page-design data again to resolve parent links
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }

- name: Restore the nico-site state data
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: state, DATA_URI: /api/state }
- name: Restore the nico-site agency data
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: agency, DATA_URI: /api/agency }
- name: Restore the nico-site reportcard
  hosts: "{{ target }}"
  roles:
    - { role: nico_site_restore_enUS, DATA_NAME_VAR: reportcard, DATA_URI: /api/reportcard }

